spring.datasource.url=jdbc:postgresql://localhost:5434/luckygame
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.data.web.pageable.max-page-size=100

game.start-points=1000

server.port=8081

